### ISSUE TITLE
Bing Scraper not working

### ISSUE THREAD

**Issue by bnew** [montoyamoraga/scrapers#1]
Hey aaron + the internet, 

Seems like the bing scraper has broken. I'm on a mac and receive the following error when trying to scrape.

query bing images
script.py:126: DeprecationWarning: use driver.switch_to.frame instead
  driver.switch_to_frame("OverlayIFrame")
Traceback (most recent call last):
  File "script.py", line 222, in <module>
    scrape(scrapeSubject)
  File "script.py", line 150, in scrape
    popup.click()

**Comment by montoyamoraga** [comment]
hey thanks for pointing it out
i don't have much time right now to address it
but i did a quick so at least it doesn't break
hope that helps in the meantime =)
